### ISSUE TITLE
repeat-until does not pick up changed javascript bindings

### ISSUE THREAD

**Issue by gtsihitas** [gwen-interpreter/gwen-web#26]
example I have this definition

And increment_current_row_number is defined by javascript "(function(){return 1 + ${current_row_number};})()"
ie
I wait until increment_current_row_number

GWEN will use the original definition and ignore the latest change

**Comment by bjuric** [comment]
Thanks @gtsihitas.  The problem was that the `repeat-until` and `repeat-while` steps were caching the initial condition. I've implemented a fix to look up the condition for every iteration in snapshot build `1.6.1-1-g69fcdbf-SNAPSHOT`. Please test that and let us know how it goes.  If all is good, we will roll out a patch release.

**Comment by bjuric** [comment]
Also note that the following should work too (without function wrapper): 
`And increment_current_row_number is defined by javascript "1 + ${current_row_number}"`

**Comment by gtsihitas** [comment]
Thanks Branko

Just tested it and it works fine now :)

**Comment by gtsihitas** [comment]
Works for both "until" and "while"

**Comment by bjuric** [comment]
Thanks @gtsihitas. I'll leave this open until we push out the fix in a release.

**Comment by bjuric** [comment]
Released in v[1.7.0](https://github.com/gwen-interpreter/gwen-web/releases/tag/v1.7.0)
