### ISSUE TITLE
Unable to assign a multi-line value or text to a meta attribute

### ISSUE THREAD

**Issue by mairbar** [gwen-interpreter/gwen-web#33]
Using regex, I am able to capture a multi-line output from a system process. However, I am unable to assign the captured value to a GWEN attribute since the execution fails with the error `Unsupported or undefined step...`

The steps go something like this:

`Given some_result is defined by system process "<some_process>"`
`Then I capture the text in some_result by regex "<some_regex>" as Multi_Line_Result`
`Given some_variable is "${Multi_Line_Result}"`
`...`

The GWEN execution fails on the second `Given` statement.
Can GWEN support assigning multi-line values/texts to a variable?
This is quite useful in checking values such as email body content within GWEN.

**Comment by bjuric** [comment]
Hi,

Looks like your second `Given` step is attempting to do a multi line assignment (which is not supported) instead of an actual assertion.  Since you already have the value captured in `Multi_Line_Result`, you should be able to use that to perform assertions like this..

`Then Multi_Line_Result should match regex "<some_regex_match>"`

Just be sure to use `(?s).*` instead of `.*` for matching over multiple lines as per http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#DOTALL

Otherwise you can use any of the other matching DSL steps..

`Then Multi_Line_Result <should|should not> <be|contain|start with|end with|match regex|match xpath> "<expression>"`

Let me know if you need more help.

**Comment by mairbar** [comment]
Thanks Branko. I updated my test to not use a multi-line assignment and `should match regex` is just the DSL I needed to assert a multi-line value.
