### ISSUE TITLE
Drag and drop support for an object via Gwen DSL

### ISSUE THREAD

**Issue by ketu4u2010** [gwen-interpreter/gwen-web#42]
Drag and drop support for an object via Gwen DSL:

At present, there is no support for Drag and drop as Standard DSL.

In case user needs to perform Drag and drop then user needs to find alternative way to achieve the same.

As a Gwen user, I feel this should be supported as a standard DSL.

Sample Website to try: http://the-internet.herokuapp.com/drag_and_drop

**Comment by bjuric** [comment]
I have tried several ways of getting this going without success using the sample website you provided. Using the [Selenium dragAndDrop function](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/interactions/Actions.html#dragAndDrop-org.openqa.selenium.WebElement-org.openqa.selenium.WebElement-) I did however observe that it does work if the physical (actual) mouse is placed over the target element in the browser at the time when the dragAndDrop operation is performed. If the mouse is anywhere else on the screen, then source element is dropped and that location instead of the target element.

Seems others have had issues with this too. I've tried all the techniques described here without success also.. https://github.com/SeleniumHQ/selenium/issues/3269
 
Anyone else had any luck with this?

**Comment by bjuric** [comment]
Drag drop support seems very problematic and unstable. For this reason, I'm thinking we not support it at this stage.

**Comment by timrsfo** [comment]
The following works for me, its a bit clunky. I can't pass WebElements or By to the drag-drop. It uses the javascript file mentioned below with css selector strings for src and dst. Unfortunately, my javascript is limited. Maybe someone with a bit more skilled in js could clean it up for general population.

[Elemental Selenium Drag N Drop](http://the-internet.herokuapp.com/drag_and_drop) - example app for testing Drag N Drop
[rcorreia/drag_and_drop_helper.js](https://gist.github.com/rcorreia/2362544) - rcorreia's javascript helper code

// create string for javascript file, removing newlines
    `try (BufferedReader br = 
    Files.newBufferedReader(Paths.get(getURIFromURL(drag_and_drop_helper.js)))) {
                dragndrop_js = br
                        .lines()
                        .collect(Collectors.joining(" "));
            } catch (IOException e) {
                log.error(e.getMessage());
            }`

`public void dragDrop(WebDriver driver, String src, String dst) {
            String js = String.format("$('%s').simulateDragDrop({ dropTarget: '%s'});",src,dst);
            JavascriptExecutor jse = (JavascriptExecutor) driver;
            jse.executeScript(dragndrop_js + js);
        }`

for details see: [Drag and Drop in selenium java](https://stackoverflow.com/questions/42198564/drag-and-drop-in-selenium-java)
