### ISSUE TITLE
Issue with enter keystroke in textarea

### ISSUE THREAD

**Issue by anshu781126** [gwen-interpreter/gwen-web#56]
Issue: I am entering some data in textarea using a loop on each line of textarea. Text area is scrollable after it has more than 4 rows. 
say loop runs for A B C D E F
in stepdef -
```
Given I send "PAGE_DOWN" to textarea
And I append "$<data>" to textarea
Then I press enter in textarea
```
OR

```
Given I send "ENTER" to textarea
```

during 4th loop after appending data system looks like this -
![image](https://user-images.githubusercontent.com/26997587/39041775-fc067d00-44a6-11e8-96f6-21842699265c.png)

at the end of 4th loop when press enter is done then system looks like this -
![image](https://user-images.githubusercontent.com/26997587/39041847-238ab616-44a7-11e8-8f74-477f9a09f207.png)

and at the end of 6th loop. system looks like this -
![image](https://user-images.githubusercontent.com/26997587/39041916-47647360-44a7-11e8-9bc1-d990e6de9570.png)

**Comment by bjuric** [comment]
I observed similar behaviour and have no explanation for why this is happening.

**Comment by bjuric** [comment]
Perhaps try and update your native web driver.

**Comment by bjuric** [comment]
Hi @anshu781126, it turns out that pressing enter does not have the same effect as sending a new line character. I've added the following DSL for inserting new lines into text fields to better support your usage above.
- [`I insert a new line in <element>`](https://github.com/gwen-interpreter/gwen-web/wiki/Supported-DSL#i-insert-a-new-line-in-element)

So instead of using `I press enter in textarea`, please use `I insert a new line in textarea` instead.

This is available in snapshot build: 
- [gwen-web-2.18.0-2-gcb60ebb-SNAPSHOT.zip](https://oss.sonatype.org/content/repositories/snapshots/org/gweninterpreter/gwen-web/2.18.0-2-gcb60ebb-SNAPSHOT/gwen-web-2.18.0-2-gcb60ebb-SNAPSHOT.zip)

Please try it out and let us know how it goes.

**Comment by anshu781126** [comment]
Many thanks @bjuric . This is working fine. please release.
