### ISSUE TITLE
DSL to validate browser popup message

### ISSUE THREAD

**Issue by anshu781126** [gwen-interpreter/gwen-web#60]
DSL to validate browser popup message

reference - https://gwen-oss.slack.com/messages/C4U352GS2/convo/C4U352GS2-1527770973.000486/?thread_ts=1527770973.000486

**Comment by bjuric** [comment]
Added 4 new DSLs to support querying alert/confirmation popup messages.  Documentation is [here](https://github.com/gwen-interpreter/gwen-web/wiki/Supported-DSL#since-2240). Please try it out the snapshot build below and let us know how it goes.
- [gwen-web-2.23.0-1-g10a212b-SNAPSHOT.zip](https://oss.sonatype.org/content/repositories/snapshots/org/gweninterpreter/gwen-web/2.23.0-1-g10a212b-SNAPSHOT/gwen-web-2.23.0-1-g10a212b-SNAPSHOT.zip)

**Comment by bjuric** [comment]
Delivered in gwen-web release [2.24.0](https://github.com/gwen-interpreter/gwen-web/releases/tag/v2.24.0). 
@anshu781126 Please close when ready. Thanks

**Comment by anshu781126** [comment]
This is working as expected. Marking this as closed.
